name: Push to main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Main branch build
    uses: ./.github/workflows/reusable-build.yaml
  deploy:
    name: Main branch deploy
    needs: build
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      workspace: ${{ github.base_ref || github.ref_name }}
    secrets:
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      cloudfront-target: ${{ secrets.CLOUDFRONT_TARGET }}



