on:
  workflow_call:

jobs:
  build-be:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build BE # TODO here --omit=dev could help but refactor is needed on package side
        run: npm install && npm run build && npm run zip

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact-be
          path: nest-lambda.zip
